name: Node.js CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/its-tinkoff
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          git pull origin main
          git status
          npm install
          npm run build
          pm2 restart app